#Default port is 8761
server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 5 # by default Eureka waits for 5 minutes for other services to register
  serviceUrl:
    defaultZone: http://localhost:${server.port}
